<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertSkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillsRepository extends \Doctrine\ORM\EntityRepository
{
}
